INSERT INTO user (email, password, roles) values ('admin@green.com', 'Password1234!', 'ROLE_USER');
INSERT INTO user (email, password, roles) values ('cfrear1@reference.com', 'sC7@O4.(VtHN3', 'ROLE_USER');
INSERT INTO user (email, password, roles) values ('cgethyn2@goo.gl', 'yY0,7e_2m!0N', 'ROLE_USER');
INSERT INTO user (email, password, roles) values ('awarton3@businesswire.com', 'gA7=QX<5y', 'ROLE_USER');
INSERT INTO user (email, password, roles) values ('kblowick4@salon.com', 'mZ8.`i+ilRKoV(E0', 'ROLE_USER');
INSERT INTO user (email, password, roles) values ('ebearne5@google.de', 'sI5),fBzgz', 'ROLE_USER');
INSERT INTO user (email, password, roles) values ('kfuentes6@wiley.com', 'rA7/VJ?J', 'ROLE_USER');
INSERT INTO user (email, password, roles) values ('fcourtonne7@about.com', 'zR0(h6fHK', 'ROLE_USER');
INSERT INTO user (email, password, roles) values ('coglassane8@ibm.com', 'kV2!G4Fb', 'ROLE_USER');
INSERT INTO user (email, password, roles) values ('kgiraudat9@china.com.cn', 'eC1$XA,"', 'ROLE_USER');
INSERT INTO user (email, password, roles) values ('merdelya@mac.com', 'eH5=dlnQ2p!', 'ROLE_USER');
INSERT INTO user (email, password, roles) values ('eelleryb@twitter.com', 'eP9)H//I|', 'ROLE_USER');


INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Wine - Saint - Bris 2002, Sauv', 'description', 393973);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Mix Pina Colada', 'description', 129131);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Olives - Morracan Dired', 'description', 90792);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Wine - Harrow Estates, Vidal', 'description', 31724);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Chips Potato Salt Vinegar 43g', 'description', 58362);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Rosemary - Primerba, Paste', 'description', 301200);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Wine - Pinot Grigio Collavini', 'description', 394948);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Wine - White, Chardonnay', 'description', 467299);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Coffee - Colombian, Portioned', 'description', 148518);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Canada Dry', 'description', 232844);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Flour Pastry Super Fine', 'description', 379597);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Squash - Pattypan, Yellow', 'description', 388398);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Rum - Mount Gay Eclipes', 'description', 164581);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Nut - Pecan, Pieces', 'description', 325891);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Cookies - Englishbay Wht', 'description', 61503);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Calypso - Pineapple Passion', 'description', 322120);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Juice - Lagoon Mango', 'description', 51703);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Wine - Alsace Riesling Reserve', 'description', 126072);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Nestea - Ice Tea, Diet', 'description', 416145);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Bacardi Raspberry', 'description', 324386);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Melon - Honey Dew', 'description', 247808);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Tea - Earl Grey', 'description', 333276);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Juice - Apple, 1.36l', 'description', 59652);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Wine - Touraine Azay - Le - Rideau', 'description', 215660);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Stainless Steel Cleaner Vision', 'description', 435861);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Sun - Dried Tomatoes', 'description', 418300);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Compound - Strawberry', 'description', 167194);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Dooleys Toffee', 'description', 370628);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Pork - Inside', 'description', 279994);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Chicken - Leg, Boneless', 'description', 67329);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Potatoes - Mini White 3 Oz', 'description', 451333);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Ocean Spray - Kiwi Strawberry', 'description', 115127);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Lemon Balm - Fresh', 'description', 52930);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Brandy Apricot', 'description', 438516);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Wine - Prosecco Valdobienne', 'description', 326223);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Cheese - Brie', 'description', 446621);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Mussels - Frozen', 'description', 366271);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Soup - Campbells Chili Veg', 'description', 138737);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Soup - Chicken And Wild Rice', 'description', 247543);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Molasses - Fancy', 'description', 465322);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Lid Coffee Cup 8oz Blk', 'description', 391782);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Beef - Sushi Flat Iron Steak', 'description', 62935);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Duck - Legs', 'description', 362563);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Gingerale - Schweppes, 355 Ml', 'description', 103136);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Bread - Rolls, Rye', 'description', 28280);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Bread - Pumpernickle, Rounds', 'description', 414899);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Broom And Broom Rack White', 'description', 296803);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Island Oasis - Banana Daiquiri', 'description', 176269);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Black Currants', 'description', 280855);
INSERT INTO product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Potatoes - Instant, Mashed', 'description', 284021);
